import './globals.css';


export const metadata = {
  title: 'Alris Wong Portfolio',
  description: 'Generated by Alris Wong',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
